/*
 * generated by Xtext 2.18.0.M3
 */
package alpha.model.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAlphaScopeProvider extends DelegatingScopeProvider {
}
