/**
 * generated by Xtext 2.15.0
 */
package alpha.commands.model.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CommandsProposalProvider extends AbstractCommandsProposalProvider {
}
