/*
 * generated by Xtext 2.12.0
 */
package alpha.ide

import alpha.AlphaRuntimeModule
import alpha.AlphaStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AlphaIdeSetup extends AlphaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new AlphaRuntimeModule, new AlphaIdeModule))
	}
	
}
