/**
 * generated by Xtext 2.13.0
 */
package alpha.alpha.impl;

import alpha.alpha.AISLBasicSet;
import alpha.alpha.AlphaPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>AISL Basic Set</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link alpha.alpha.impl.AISLBasicSetImpl#getDims <em>Dims</em>}</li>
 *   <li>{@link alpha.alpha.impl.AISLBasicSetImpl#getConstraintString <em>Constraint String</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AISLBasicSetImpl extends MinimalEObjectImpl.Container implements AISLBasicSet
{
  /**
   * The default value of the '{@link #getDims() <em>Dims</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDims()
   * @generated
   * @ordered
   */
  protected static final String DIMS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDims() <em>Dims</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDims()
   * @generated
   * @ordered
   */
  protected String dims = DIMS_EDEFAULT;

  /**
   * The default value of the '{@link #getConstraintString() <em>Constraint String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstraintString()
   * @generated
   * @ordered
   */
  protected static final String CONSTRAINT_STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getConstraintString() <em>Constraint String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstraintString()
   * @generated
   * @ordered
   */
  protected String constraintString = CONSTRAINT_STRING_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AISLBasicSetImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AlphaPackage.Literals.AISL_BASIC_SET;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDims()
  {
    return dims;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDims(String newDims)
  {
    String oldDims = dims;
    dims = newDims;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AlphaPackage.AISL_BASIC_SET__DIMS, oldDims, dims));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getConstraintString()
  {
    return constraintString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setConstraintString(String newConstraintString)
  {
    String oldConstraintString = constraintString;
    constraintString = newConstraintString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AlphaPackage.AISL_BASIC_SET__CONSTRAINT_STRING, oldConstraintString, constraintString));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AlphaPackage.AISL_BASIC_SET__DIMS:
        return getDims();
      case AlphaPackage.AISL_BASIC_SET__CONSTRAINT_STRING:
        return getConstraintString();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AlphaPackage.AISL_BASIC_SET__DIMS:
        setDims((String)newValue);
        return;
      case AlphaPackage.AISL_BASIC_SET__CONSTRAINT_STRING:
        setConstraintString((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AlphaPackage.AISL_BASIC_SET__DIMS:
        setDims(DIMS_EDEFAULT);
        return;
      case AlphaPackage.AISL_BASIC_SET__CONSTRAINT_STRING:
        setConstraintString(CONSTRAINT_STRING_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AlphaPackage.AISL_BASIC_SET__DIMS:
        return DIMS_EDEFAULT == null ? dims != null : !DIMS_EDEFAULT.equals(dims);
      case AlphaPackage.AISL_BASIC_SET__CONSTRAINT_STRING:
        return CONSTRAINT_STRING_EDEFAULT == null ? constraintString != null : !CONSTRAINT_STRING_EDEFAULT.equals(constraintString);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (dims: ");
    result.append(dims);
    result.append(", constraintString: ");
    result.append(constraintString);
    result.append(')');
    return result.toString();
  }

} //AISLBasicSetImpl
