/**
 * generated by Xtext 2.13.0
 */
package alpha.alpha.impl;

import alpha.alpha.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class AlphaFactoryImpl extends EFactoryImpl implements AlphaFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static AlphaFactory init()
  {
    try
    {
      AlphaFactory theAlphaFactory = (AlphaFactory)EPackage.Registry.INSTANCE.getEFactory(AlphaPackage.eNS_URI);
      if (theAlphaFactory != null)
      {
        return theAlphaFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new AlphaFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AlphaFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case AlphaPackage.ASTART: return createAStart();
      case AlphaPackage.ABSTRACT_ELEMENT: return createAbstractElement();
      case AlphaPackage.APACKAGE_DECLARATION: return createAPackageDeclaration();
      case AlphaPackage.AIMPORT: return createAImport();
      case AlphaPackage.ACONSTANT_DECLARATION: return createAConstantDeclaration();
      case AlphaPackage.AEXTERNAL_FUNCTION_DECLARATION: return createAExternalFunctionDeclaration();
      case AlphaPackage.AEXTERNAL_FUNCTION: return createAExternalFunction();
      case AlphaPackage.ACONSTANT: return createAConstant();
      case AlphaPackage.AAFFINE_SYSTEM: return createAAffineSystem();
      case AlphaPackage.AVARIABLE_DECLARATION: return createAVariableDeclaration();
      case AlphaPackage.AVARIABLE_LIST: return createAVariableList();
      case AlphaPackage.AVARIABLE: return createAVariable();
      case AlphaPackage.AFUZZY_VARIABLE_DECLARATION: return createAFuzzyVariableDeclaration();
      case AlphaPackage.POLYHEDRAL_OBJECT: return createPolyhedralObject();
      case AlphaPackage.APOLYHEDRAL_OBJECT_EXPRESSION: return createAPolyhedralObjectExpression();
      case AlphaPackage.AVARIABLE_DOMAIN: return createAVariableDomain();
      case AlphaPackage.ARECTANGULAR_DOMAIN: return createARectangularDomain();
      case AlphaPackage.ADECLARED_OBJECT: return createADeclaredObject();
      case AlphaPackage.AISL_SET: return createAISLSet();
      case AlphaPackage.AISL_BASIC_SET: return createAISLBasicSet();
      case AlphaPackage.AISL_RELATION: return createAISLRelation();
      case AlphaPackage.AISL_BASIC_RELATION: return createAISLBasicRelation();
      case AlphaPackage.AEQUATION: return createAEquation();
      case AlphaPackage.AUSE_EQUATION: return createAUseEquation();
      case AlphaPackage.AALPHA_EXPRESSION: return createAAlphaExpression();
      case AlphaPackage.ANOT_EXPRESSION: return createANotExpression();
      case AlphaPackage.ANEGATE_EXPRESSION: return createANegateExpression();
      case AlphaPackage.ACASE_EXPRESSION: return createACaseExpression();
      case AlphaPackage.ADEPENDENCE_EXPRESSION: return createADependenceExpression();
      case AlphaPackage.ASELECT_DEPENDENCE_EXPRESSION: return createASelectDependenceExpression();
      case AlphaPackage.ADEPENDENCE_IN_ARRAY_NOTATION: return createADependenceInArrayNotation();
      case AlphaPackage.AIF_EXPRESSION: return createAIfExpression();
      case AlphaPackage.AINDEX_EXPRESSION: return createAIndexExpression();
      case AlphaPackage.AINDEX_EXPRESSION_IN_ARRAY_NOTATION: return createAIndexExpressionInArrayNotation();
      case AlphaPackage.AREDUCE_EXPRESSION: return createAReduceExpression();
      case AlphaPackage.AARG_REDUCE_EXPRESSION: return createAArgReduceExpression();
      case AlphaPackage.ACONV_EXPRESSION: return createAConvExpression();
      case AlphaPackage.ARESTRICT_EXPRESSION: return createARestrictExpression();
      case AlphaPackage.APOLY_OBJECT_IN_RESTRICT: return createAPolyObjectInRestrict();
      case AlphaPackage.AAUTO_RESTRICT_EXPRESSION: return createAAutoRestrictExpression();
      case AlphaPackage.AVARIABLE_EXPRESSION: return createAVariableExpression();
      case AlphaPackage.ACONSTANT_EXPRESSION: return createAConstantExpression();
      case AlphaPackage.ABOOLEAN_EXPRESSION: return createABooleanExpression();
      case AlphaPackage.AINTEGER_EXPRESSION: return createAIntegerExpression();
      case AlphaPackage.AREAL_EXPRESSION: return createARealExpression();
      case AlphaPackage.AMULTI_ARG_EXPRESSION: return createAMultiArgExpression();
      case AlphaPackage.AMULTI_ARG_ARITHMETIC_EXPRESSION: return createAMultiArgArithmeticExpression();
      case AlphaPackage.AMULTI_ARG_LOGICAL_EXPRESSION: return createAMultiArgLogicalExpression();
      case AlphaPackage.AEXTERNAL_FUNCTION_CALL: return createAExternalFunctionCall();
      case AlphaPackage.AINDEX_AFFINE_EXPRESSION_LIST: return createAIndexAffineExpressionList();
      case AlphaPackage.AFUNCTION: return createAFunction();
      case AlphaPackage.AFUNCTION_IN_ARRAY_NOTATION: return createAFunctionInArrayNotation();
      case AlphaPackage.AREDUCTION_OPERATOR: return createAReductionOperator();
      case AlphaPackage.ABINARY_POLY_OBJ_EXPRESSION: return createABinaryPolyObjExpression();
      case AlphaPackage.AOR_EXPRESSION: return createAOrExpression();
      case AlphaPackage.AAND_EXPRESSION: return createAAndExpression();
      case AlphaPackage.ARELATIONAL_EXPRESSION: return createARelationalExpression();
      case AlphaPackage.AADDITIVE_EXPRESSION: return createAAdditiveExpression();
      case AlphaPackage.AMULTIPLICATIVE_EXPRESSION: return createAMultiplicativeExpression();
      case AlphaPackage.AMIN_MAX_EXPRESSION: return createAMinMaxExpression();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AStart createAStart()
  {
    AStartImpl aStart = new AStartImpl();
    return aStart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractElement createAbstractElement()
  {
    AbstractElementImpl abstractElement = new AbstractElementImpl();
    return abstractElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public APackageDeclaration createAPackageDeclaration()
  {
    APackageDeclarationImpl aPackageDeclaration = new APackageDeclarationImpl();
    return aPackageDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AImport createAImport()
  {
    AImportImpl aImport = new AImportImpl();
    return aImport;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AConstantDeclaration createAConstantDeclaration()
  {
    AConstantDeclarationImpl aConstantDeclaration = new AConstantDeclarationImpl();
    return aConstantDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AExternalFunctionDeclaration createAExternalFunctionDeclaration()
  {
    AExternalFunctionDeclarationImpl aExternalFunctionDeclaration = new AExternalFunctionDeclarationImpl();
    return aExternalFunctionDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AExternalFunction createAExternalFunction()
  {
    AExternalFunctionImpl aExternalFunction = new AExternalFunctionImpl();
    return aExternalFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AConstant createAConstant()
  {
    AConstantImpl aConstant = new AConstantImpl();
    return aConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AAffineSystem createAAffineSystem()
  {
    AAffineSystemImpl aAffineSystem = new AAffineSystemImpl();
    return aAffineSystem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AVariableDeclaration createAVariableDeclaration()
  {
    AVariableDeclarationImpl aVariableDeclaration = new AVariableDeclarationImpl();
    return aVariableDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AVariableList createAVariableList()
  {
    AVariableListImpl aVariableList = new AVariableListImpl();
    return aVariableList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AVariable createAVariable()
  {
    AVariableImpl aVariable = new AVariableImpl();
    return aVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AFuzzyVariableDeclaration createAFuzzyVariableDeclaration()
  {
    AFuzzyVariableDeclarationImpl aFuzzyVariableDeclaration = new AFuzzyVariableDeclarationImpl();
    return aFuzzyVariableDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PolyhedralObject createPolyhedralObject()
  {
    PolyhedralObjectImpl polyhedralObject = new PolyhedralObjectImpl();
    return polyhedralObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public APolyhedralObjectExpression createAPolyhedralObjectExpression()
  {
    APolyhedralObjectExpressionImpl aPolyhedralObjectExpression = new APolyhedralObjectExpressionImpl();
    return aPolyhedralObjectExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AVariableDomain createAVariableDomain()
  {
    AVariableDomainImpl aVariableDomain = new AVariableDomainImpl();
    return aVariableDomain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ARectangularDomain createARectangularDomain()
  {
    ARectangularDomainImpl aRectangularDomain = new ARectangularDomainImpl();
    return aRectangularDomain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ADeclaredObject createADeclaredObject()
  {
    ADeclaredObjectImpl aDeclaredObject = new ADeclaredObjectImpl();
    return aDeclaredObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AISLSet createAISLSet()
  {
    AISLSetImpl aislSet = new AISLSetImpl();
    return aislSet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AISLBasicSet createAISLBasicSet()
  {
    AISLBasicSetImpl aislBasicSet = new AISLBasicSetImpl();
    return aislBasicSet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AISLRelation createAISLRelation()
  {
    AISLRelationImpl aislRelation = new AISLRelationImpl();
    return aislRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AISLBasicRelation createAISLBasicRelation()
  {
    AISLBasicRelationImpl aislBasicRelation = new AISLBasicRelationImpl();
    return aislBasicRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AEquation createAEquation()
  {
    AEquationImpl aEquation = new AEquationImpl();
    return aEquation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AUseEquation createAUseEquation()
  {
    AUseEquationImpl aUseEquation = new AUseEquationImpl();
    return aUseEquation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AAlphaExpression createAAlphaExpression()
  {
    AAlphaExpressionImpl aAlphaExpression = new AAlphaExpressionImpl();
    return aAlphaExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ANotExpression createANotExpression()
  {
    ANotExpressionImpl aNotExpression = new ANotExpressionImpl();
    return aNotExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ANegateExpression createANegateExpression()
  {
    ANegateExpressionImpl aNegateExpression = new ANegateExpressionImpl();
    return aNegateExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ACaseExpression createACaseExpression()
  {
    ACaseExpressionImpl aCaseExpression = new ACaseExpressionImpl();
    return aCaseExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ADependenceExpression createADependenceExpression()
  {
    ADependenceExpressionImpl aDependenceExpression = new ADependenceExpressionImpl();
    return aDependenceExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ASelectDependenceExpression createASelectDependenceExpression()
  {
    ASelectDependenceExpressionImpl aSelectDependenceExpression = new ASelectDependenceExpressionImpl();
    return aSelectDependenceExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ADependenceInArrayNotation createADependenceInArrayNotation()
  {
    ADependenceInArrayNotationImpl aDependenceInArrayNotation = new ADependenceInArrayNotationImpl();
    return aDependenceInArrayNotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AIfExpression createAIfExpression()
  {
    AIfExpressionImpl aIfExpression = new AIfExpressionImpl();
    return aIfExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AIndexExpression createAIndexExpression()
  {
    AIndexExpressionImpl aIndexExpression = new AIndexExpressionImpl();
    return aIndexExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AIndexExpressionInArrayNotation createAIndexExpressionInArrayNotation()
  {
    AIndexExpressionInArrayNotationImpl aIndexExpressionInArrayNotation = new AIndexExpressionInArrayNotationImpl();
    return aIndexExpressionInArrayNotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AReduceExpression createAReduceExpression()
  {
    AReduceExpressionImpl aReduceExpression = new AReduceExpressionImpl();
    return aReduceExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AArgReduceExpression createAArgReduceExpression()
  {
    AArgReduceExpressionImpl aArgReduceExpression = new AArgReduceExpressionImpl();
    return aArgReduceExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AConvExpression createAConvExpression()
  {
    AConvExpressionImpl aConvExpression = new AConvExpressionImpl();
    return aConvExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ARestrictExpression createARestrictExpression()
  {
    ARestrictExpressionImpl aRestrictExpression = new ARestrictExpressionImpl();
    return aRestrictExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public APolyObjectInRestrict createAPolyObjectInRestrict()
  {
    APolyObjectInRestrictImpl aPolyObjectInRestrict = new APolyObjectInRestrictImpl();
    return aPolyObjectInRestrict;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AAutoRestrictExpression createAAutoRestrictExpression()
  {
    AAutoRestrictExpressionImpl aAutoRestrictExpression = new AAutoRestrictExpressionImpl();
    return aAutoRestrictExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AVariableExpression createAVariableExpression()
  {
    AVariableExpressionImpl aVariableExpression = new AVariableExpressionImpl();
    return aVariableExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AConstantExpression createAConstantExpression()
  {
    AConstantExpressionImpl aConstantExpression = new AConstantExpressionImpl();
    return aConstantExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ABooleanExpression createABooleanExpression()
  {
    ABooleanExpressionImpl aBooleanExpression = new ABooleanExpressionImpl();
    return aBooleanExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AIntegerExpression createAIntegerExpression()
  {
    AIntegerExpressionImpl aIntegerExpression = new AIntegerExpressionImpl();
    return aIntegerExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ARealExpression createARealExpression()
  {
    ARealExpressionImpl aRealExpression = new ARealExpressionImpl();
    return aRealExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AMultiArgExpression createAMultiArgExpression()
  {
    AMultiArgExpressionImpl aMultiArgExpression = new AMultiArgExpressionImpl();
    return aMultiArgExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AMultiArgArithmeticExpression createAMultiArgArithmeticExpression()
  {
    AMultiArgArithmeticExpressionImpl aMultiArgArithmeticExpression = new AMultiArgArithmeticExpressionImpl();
    return aMultiArgArithmeticExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AMultiArgLogicalExpression createAMultiArgLogicalExpression()
  {
    AMultiArgLogicalExpressionImpl aMultiArgLogicalExpression = new AMultiArgLogicalExpressionImpl();
    return aMultiArgLogicalExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AExternalFunctionCall createAExternalFunctionCall()
  {
    AExternalFunctionCallImpl aExternalFunctionCall = new AExternalFunctionCallImpl();
    return aExternalFunctionCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AIndexAffineExpressionList createAIndexAffineExpressionList()
  {
    AIndexAffineExpressionListImpl aIndexAffineExpressionList = new AIndexAffineExpressionListImpl();
    return aIndexAffineExpressionList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AFunction createAFunction()
  {
    AFunctionImpl aFunction = new AFunctionImpl();
    return aFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AFunctionInArrayNotation createAFunctionInArrayNotation()
  {
    AFunctionInArrayNotationImpl aFunctionInArrayNotation = new AFunctionInArrayNotationImpl();
    return aFunctionInArrayNotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AReductionOperator createAReductionOperator()
  {
    AReductionOperatorImpl aReductionOperator = new AReductionOperatorImpl();
    return aReductionOperator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ABinaryPolyObjExpression createABinaryPolyObjExpression()
  {
    ABinaryPolyObjExpressionImpl aBinaryPolyObjExpression = new ABinaryPolyObjExpressionImpl();
    return aBinaryPolyObjExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AOrExpression createAOrExpression()
  {
    AOrExpressionImpl aOrExpression = new AOrExpressionImpl();
    return aOrExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AAndExpression createAAndExpression()
  {
    AAndExpressionImpl aAndExpression = new AAndExpressionImpl();
    return aAndExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ARelationalExpression createARelationalExpression()
  {
    ARelationalExpressionImpl aRelationalExpression = new ARelationalExpressionImpl();
    return aRelationalExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AAdditiveExpression createAAdditiveExpression()
  {
    AAdditiveExpressionImpl aAdditiveExpression = new AAdditiveExpressionImpl();
    return aAdditiveExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AMultiplicativeExpression createAMultiplicativeExpression()
  {
    AMultiplicativeExpressionImpl aMultiplicativeExpression = new AMultiplicativeExpressionImpl();
    return aMultiplicativeExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AMinMaxExpression createAMinMaxExpression()
  {
    AMinMaxExpressionImpl aMinMaxExpression = new AMinMaxExpressionImpl();
    return aMinMaxExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AlphaPackage getAlphaPackage()
  {
    return (AlphaPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static AlphaPackage getPackage()
  {
    return AlphaPackage.eINSTANCE;
  }

} //AlphaFactoryImpl
