/**
 * generated by Xtext 2.12.0
 */
package alpha.alpha;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AConstant Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see alpha.alpha.AlphaPackage#getAConstantExpression()
 * @model
 * @generated
 */
public interface AConstantExpression extends AAlphaExpression
{
} // AConstantExpression
