/**
 * generated by Xtext 2.12.0
 */
package alpha.alpha;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ADependence Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link alpha.alpha.ADependenceExpression#getFunction <em>Function</em>}</li>
 *   <li>{@link alpha.alpha.ADependenceExpression#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see alpha.alpha.AlphaPackage#getADependenceExpression()
 * @model
 * @generated
 */
public interface ADependenceExpression extends AAlphaExpression
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' containment reference.
   * @see #setFunction(AFunction)
   * @see alpha.alpha.AlphaPackage#getADependenceExpression_Function()
   * @model containment="true"
   * @generated
   */
  AFunction getFunction();

  /**
   * Sets the value of the '{@link alpha.alpha.ADependenceExpression#getFunction <em>Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' containment reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(AFunction value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(AAlphaExpression)
   * @see alpha.alpha.AlphaPackage#getADependenceExpression_Expr()
   * @model containment="true"
   * @generated
   */
  AAlphaExpression getExpr();

  /**
   * Sets the value of the '{@link alpha.alpha.ADependenceExpression#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(AAlphaExpression value);

} // ADependenceExpression
