/**
 * generated by Xtext 2.12.0
 */
package alpha.alpha;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AExternal Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link alpha.alpha.AExternalFunction#getName <em>Name</em>}</li>
 *   <li>{@link alpha.alpha.AExternalFunction#getInputCardinarity <em>Input Cardinarity</em>}</li>
 * </ul>
 *
 * @see alpha.alpha.AlphaPackage#getAExternalFunction()
 * @model
 * @generated
 */
public interface AExternalFunction extends AExternalFunctionDeclaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see alpha.alpha.AlphaPackage#getAExternalFunction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link alpha.alpha.AExternalFunction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Input Cardinarity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Input Cardinarity</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Cardinarity</em>' attribute.
   * @see #setInputCardinarity(int)
   * @see alpha.alpha.AlphaPackage#getAExternalFunction_InputCardinarity()
   * @model
   * @generated
   */
  int getInputCardinarity();

  /**
   * Sets the value of the '{@link alpha.alpha.AExternalFunction#getInputCardinarity <em>Input Cardinarity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input Cardinarity</em>' attribute.
   * @see #getInputCardinarity()
   * @generated
   */
  void setInputCardinarity(int value);

} // AExternalFunction
