/**
 * generated by Xtext 2.12.0
 */
package alpha.alpha;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AIndex Expression In Array Notation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link alpha.alpha.AIndexExpressionInArrayNotation#getFunc <em>Func</em>}</li>
 * </ul>
 *
 * @see alpha.alpha.AlphaPackage#getAIndexExpressionInArrayNotation()
 * @model
 * @generated
 */
public interface AIndexExpressionInArrayNotation extends AAlphaExpression
{
  /**
   * Returns the value of the '<em><b>Func</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' attribute.
   * @see #setFunc(String)
   * @see alpha.alpha.AlphaPackage#getAIndexExpressionInArrayNotation_Func()
   * @model
   * @generated
   */
  String getFunc();

  /**
   * Sets the value of the '{@link alpha.alpha.AIndexExpressionInArrayNotation#getFunc <em>Func</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func</em>' attribute.
   * @see #getFunc()
   * @generated
   */
  void setFunc(String value);

} // AIndexExpressionInArrayNotation
