/*
 * generated by Xtext 2.15.0
 */
package alpha.commands.model.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCommandsScopeProvider extends DelegatingScopeProvider {
}
