/*
 * generated by Xtext 2.22.0
 */
package alpha.model.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.EObjectNode;

import alpha.model.CalculatorExpression;
import alpha.model.DependenceExpression;
import alpha.model.RestrictExpression;
import alpha.model.VariableExpression;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class AlphaOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
	protected void _createNode(EObjectNode parentNode, CalculatorExpression cexp) {
		if (parentNode.getEClass().getInstanceClass() == RestrictExpression.class) return;
		
		super._createNode(parentNode, cexp);
	}
	
	protected void _createNode(EObjectNode parentNode, VariableExpression vexp) {
		if (parentNode.getEClass().getInstanceClass() == DependenceExpression.class) return;
		
		super._createNode(parentNode, vexp);
	}
}
