/**
 * generated by Xtext 2.13.0
 */
package alpha.model;

import alpha.model.AlphaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AlphaStandaloneSetup extends AlphaStandaloneSetupGenerated {
  public static void doSetup() {
    new AlphaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
