/**
 * generated by Xtext 2.15.0
 */
package alpha.commands.model.ide;

import alpha.commands.model.CommandsRuntimeModule;
import alpha.commands.model.CommandsStandaloneSetup;
import alpha.commands.model.ide.CommandsIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CommandsIdeSetup extends CommandsStandaloneSetup {
  @Override
  public Injector createInjector() {
    CommandsRuntimeModule _commandsRuntimeModule = new CommandsRuntimeModule();
    CommandsIdeModule _commandsIdeModule = new CommandsIdeModule();
    return Guice.createInjector(Modules2.mixin(_commandsRuntimeModule, _commandsIdeModule));
  }
}
