/**
 * generated by Xtext 2.12.0
 */
package alpha.ui.contentassist;

import alpha.ui.contentassist.AbstractAlphaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AlphaProposalProvider extends AbstractAlphaProposalProvider {
}
