/**
 * generated by Xtext 2.15.0
 */
package alpha.commands.model;

import alpha.commands.model.AbstractCommandsRuntimeModule;
import alpha.commands.model.scoping.CommandsQualifiedNameProvider;
import fr.irisa.cairn.xtend.protectedregion.ProtectedRegionResolverAsPostProcessor;
import org.eclipse.xtext.generator.IFilePostProcessor;
import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CommandsRuntimeModule extends AbstractCommandsRuntimeModule {
  public Class<? extends IFilePostProcessor> bindPostProcessor() {
    return ProtectedRegionResolverAsPostProcessor.class;
  }
  
  @Override
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return CommandsQualifiedNameProvider.class;
  }
}
