/**
 * generated by Xtext 2.18.0.M3
 */
package alpha.targetmapping.ide;

import alpha.targetmapping.TargetMappingRuntimeModule;
import alpha.targetmapping.TargetMappingStandaloneSetup;
import alpha.targetmapping.ide.TargetMappingIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TargetMappingIdeSetup extends TargetMappingStandaloneSetup {
  @Override
  public Injector createInjector() {
    TargetMappingRuntimeModule _targetMappingRuntimeModule = new TargetMappingRuntimeModule();
    TargetMappingIdeModule _targetMappingIdeModule = new TargetMappingIdeModule();
    return Guice.createInjector(Modules2.mixin(_targetMappingRuntimeModule, _targetMappingIdeModule));
  }
}
