/**
 * generated by Xtext 2.12.0
 */
package alpha.ui;

import alpha.ui.AbstractAlphaUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AlphaUiModule extends AbstractAlphaUiModule {
  public AlphaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
