/*
 * generated by Xtext 2.22.0
 */
package alpha.targetmapping.ide;


/**
 * Use this class to register ide components.
 */
public class TargetMappingIdeModule extends AbstractTargetMappingIdeModule {
}
