/*
 * generated by Xtext 2.22.0
 */
package alpha.targetmapping;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.parser.IAstFactory;

import alpha.targetmapping.construction.TargetMappingCustomASTFactory;
import alpha.targetmapping.construction.TargetMappingCustomValueConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TargetMappingRuntimeModule extends AbstractTargetMappingRuntimeModule {
	
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return TargetMappingCustomValueConverter.class;
	}
	
	@Override
	public Class<? extends IAstFactory> bindIAstFactory() {
		return TargetMappingCustomASTFactory.class;
	}
}
