/**
 * generated by Xtext 2.13.0
 */
package alpha.model.formatting2;

import alpha.model.AlphaPackage;
import alpha.model.AlphaRoot;
import alpha.model.services.AlphaGrammarAccess;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class AlphaFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private AlphaGrammarAccess _alphaGrammarAccess;
  
  protected void _format(final AlphaRoot alphaRoot, @Extension final IFormattableDocument document) {
  }
  
  protected void _format(final AlphaPackage alphaPackage, @Extension final IFormattableDocument document) {
  }
  
  public void format(final Object alphaPackage, final IFormattableDocument document) {
    if (alphaPackage instanceof AlphaPackage) {
      _format((AlphaPackage)alphaPackage, document);
      return;
    } else if (alphaPackage instanceof AlphaRoot) {
      _format((AlphaRoot)alphaPackage, document);
      return;
    } else if (alphaPackage instanceof XtextResource) {
      _format((XtextResource)alphaPackage, document);
      return;
    } else if (alphaPackage instanceof EObject) {
      _format((EObject)alphaPackage, document);
      return;
    } else if (alphaPackage == null) {
      _format((Void)null, document);
      return;
    } else if (alphaPackage != null) {
      _format(alphaPackage, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(alphaPackage, document).toString());
    }
  }
}
