/*
 * generated by Xtext 2.22.0
 */
package alpha.model.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.hover.html.IEObjectHoverDocumentationProvider;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AlphaUiModule extends AbstractAlphaUiModule {

	public AlphaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(IEObjectHoverProvider.class).to(AlphaEObjectHoverProvider.class);
		binder.bind(IEObjectHoverDocumentationProvider.class).to(AlphaEObjectHoverDocumentationProvider.class);
	}
}
